name: tape
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - blas=1.0=mkl
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cycler=0.10.0
  # - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.2.10
  # - fontconfig=2.13.0
  - freetype=2.10.4
  # - glib=2.63.1
  # - gst-plugins-base=1.14.0
  # - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - joblib=1.0.0
  - jpeg=9b
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - kiwisolver=1.3.0
  - lcms2=2.11
  # - libedit=3.1.20191231
  - libffi=3.2.1
  # - libgcc-ng=9.1.0
  # - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  # - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  # - libuuid=1.0.3
  # - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2=256
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  # - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pandas=1.1.5
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.3
  - prompt-toolkit=3.0.8
  - ptyprocess=0.6.0
  - pygments=2.7.3
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.4
  - python-dateutil=2.8.1
  - pytz=2020.5
  - pyzmq=20.0.0
  - qt=5.9.7
  # - readline=7.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.1
  - setuptools=51.0.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - biopython==1.78
    - boto3==1.16.45
    - botocore==1.19.45
    - jmespath==0.10.0
    - lmdb==1.0.0
    - protobuf==3.14.0
    - s3transfer==0.3.3
    - tape-proteins==0.4
    - tensorboardx==2.1
    - torch==1.4.0
    - torchvision==0.5.0
    - tqdm==4.55.0
